# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches: [ "main" ]
    paths:
      - "__init__.py"
  workflow_dispatch: {}

jobs:
  build_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Loading job.
      uses: actions/checkout@v3
    - name: Setting up Python 3.10.
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Installing dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install "bdx_work_shop" "psutil" "requests" "pymysql" "qrcode" "websocket-client" "brotli" "pillow" "rich" "numpy" "pyinstaller" "mido" "pycryptodome" "wget" "flashtext"
    - name: Building exe.
      run: |
        cd ./build/
        pyinstaller --upx-dir ./upx/Linux_amd64/ -F ./robot.py
        mv ./dist/robot .
        ./upx/Linux_amd64/upx --ultra-brute ./robot
    - name: Uploading to Github.
      run: |
        cd ./build/
        echo Setting config.
        git config --global user.email "wzm0529@163.com"
        git config --global user.name "xX7912Xx"
        echo Initing git.
        git init
        git remote add origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/xX7912Xx/DotCS.git
        git config --global core.autocrlf false
        echo Loading files.
        git add ./robot
        echo Setting commit.
        git commit -m "Github Action"
        echo Setting branch.
        git branch -M "GithubActionLinux"
        echo Pushing.
        git push -f -u origin "GithubActionLinux"
        echo Finished.



  build_Windows:
    runs-on: windows-latest
    steps:
    - name: Loading job.
      uses: actions/checkout@v3
    - name: Setting up Python 3.10.
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installing dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install "bdx_work_shop" "psutil" "requests" "pymysql" "qrcode" "websocket-client" "brotli" "pillow" "rich" "numpy" "pyinstaller" "mido" "pycryptodome" "wget" "flashtext"
    - name: Building exe.
      run: |
        cd build
        cmd.exe /c build.cmd
    - name: Uploading to Github.
      run: |
        cd build
        echo Setting config.
        git config --global user.email "wzm0529@163.com"
        git config --global user.name "xX7912Xx"
        echo Initing git.
        git init
        git remote add origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/xX7912Xx/DotCS.git
        git config --global core.autocrlf false
        echo Loading files.
        git add robot.exe
        echo Setting commit.
        git commit -m "Github Action"
        echo Setting branch.
        git branch -M "GithubActionWindows"
        echo Pushing.
        git push -f -u origin "GithubActionWindows"
        echo Finished.
