# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches: [ "main" ]
    paths:
      - "version"
      - "__init__.py"
  workflow_dispatch: {}

jobs:
  build_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Loading job.
      uses: actions/checkout@v3
    - name: Setting up Python 3.10.
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Installing dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Building exe.
      run: |
        pyinstaller -F ./__init__.py
        cp ./dist/__init__ DotCS_community

    - name: Archive binaries
      run: |
        tar -czf all.tar.gz *
        
    - name: Provide release version
      id: release_version
      run: echo "release_version=$(cat version)"  >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: RP${{ steps.release_version.outputs.release_version }}
        files: |
          DotCS_community
          all.tar.gz
