# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches: [ "main" ]
    paths:
      - "__init__.py"
  workflow_dispatch: {}

jobs:
  build_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Loading job.
      uses: actions/checkout@v3
    - name: Setting up Python 3.10.
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Installing dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Building exe.
      run: |
        pyinstaller -F ./__init__.py
        cp ./dist/__init__ DotCS_community

    - name: Uploading to Github.
      run: |
        echo Setting config.
        git config --global user.email "wzm0529@163.com"
        git config --global user.name "xX7912Xx"
        echo Initing git.
        git init
        git remote add origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/xX7912Xx/DotCS.git
        git config --global core.autocrlf false
        echo Loading files.
        git add ./DotCS_community
        echo Setting commit.
        git commit -m "Github Action"
        echo Setting branch.
        git branch -M "GithubActionLinux"
        echo Pushing.
        git push -f -u origin "GithubActionLinux"
        echo Finished.
